### Numpy 공부
과제를 하면서 알게되는 numpy 함수들에 대한 공부!

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized version: " + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("For loop: " + str(1000*(toc-tic)) + "ms")

249604.74573504113
Vectorized version: 13.777971267700195ms
249604.7457350354
For loop: 522.226095199585ms


### Broadcasting in Python

In [4]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])

In [5]:
cal = A.sum(axis = 0)
print(cal)

[ 59.  239.  155.4  76.9]


In [6]:
percentage = 100 * A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


### A note on python/numpy vectors

In [7]:
import numpy as np

a = np.random.randn(5)  
# Do not use like this!
# a = np.random.randn(5,1) -> a.shape = (5,1) Column vector
# a = np.random.randn(1,5) -> a.shape = (1,5) Row vector

In [8]:
print(a)

[-1.33124141  1.26672546 -1.10662864 -0.01969639  0.07169855]


In [9]:
print(a.shape)

(5,)


In [10]:
print(a.T)

[-1.33124141  1.26672546 -1.10662864 -0.01969639  0.07169855]


In [13]:
print(a.T)

[[-0.67991417  0.32999665 -0.55953791  1.28168651  0.16023366]]


In [20]:
a = np.random.randn(5,1)
print(a)

[[ 0.60837452]
 [-0.42553472]
 [ 1.28458917]
 [-0.8127905 ]
 [ 0.78193135]]


In [11]:
print(np.dot(a, a.T))

4.606952649069482


In [14]:
print(np.dot(a,a.T))

[[ 0.46228329 -0.2243694   0.38043776 -0.87143683 -0.10894514]
 [-0.2243694   0.10889779 -0.18464564  0.42295225  0.05287657]
 [ 0.38043776 -0.18464564  0.31308268 -0.71715219 -0.08965681]
 [-0.87143683  0.42295225 -0.71715219  1.64272031  0.20536933]
 [-0.10894514  0.05287657 -0.08965681  0.20536933  0.02567483]]


In [15]:
a = np.random.randn(12288, 150)
b = np.random.randn(150,45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)


In [16]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = np.dot(a,b)
print(c.shape)

(4, 2)


In [17]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
print(c.shape)

(2, 3)


In [18]:
A = np.random.randn(4,3)
B = np.sum(A, axis =1, keepdims = True)
print(B.shape)

(4, 1)
